### ISSUE TITLE
Snoqualmie misspelled as Snowquaminie

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-permit-platform#122]
## Notes
Snoqualmie misspelled as Snowquaminie on "Your activity requires a permit, but not one available online.

## Acceptance Criteria
spell as Snoqualmie

## Tasks
fix spelling error
## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [X ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
