### ISSUE TITLE
As a FS employee, I want to be directed to the main eAuth, so that I can log in

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#148]
## Notes
"Directed" refers to the redirect that happens based on env variables

## Acceptance Criteria
- [ ]

## Tasks
- [ ] Generate certs and submit to USDA ICAM
- [ ] Change VCAP endpoint and certs to production 
- [ ] Contact eAuth folks in USDA ICAM to get approvals

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
@lauraGgit to confirm whether we can do this with ATT, or if we need to wait for ATO

**Comment by msadakFS** [comment]
Is this blocked or can we do this now?

**Comment by lauraGgit** [comment]
@msadakFS Yes, it is blocked. There is an administrative side prerequisite and we know what we need to get that process started to unblock this.

**Comment by msadakFS** [comment]
Information needed to unblock the Prod eAuth ticket:
1. The ISA to be completed. This might already be done; Katherine Martinez could confirm whether this is the case. @aaron_burk_usfs 
2. A quick email from the application business owner, Aaron Burk, stating that ePermits has been tested and requesting that it go to production and by what date it will be needed. A reply to this thread would be fine. Please allow us at least two weeks' lead time. Prod changes are implemented Mondays and Wednesdays (except holidays) between 5pm-10pm Eastern Time. @aaron_burk_usfs 
3. Technical information about your production SAML endpoint. If you can generate and send me SP metadata as an XML file, that would be the fastest way for me to prepare the prod change request. @laura

**Comment by msadakFS** [comment]
Information needed to unblock the Prod eAuth ticket (thanks Laura):
1. The ISA to be completed. This might already be done; Katherine Martinez could confirm whether this is the case. @aaronburk 
2. A quick email from the application business owner, Aaron Burk, stating that ePermits has been tested and requesting that it go to production and by what date it will be needed. A reply to this thread would be fine. Please allow us at least two weeks' lead time. Prod changes are implemented Mondays and Wednesdays (except holidays) between 5pm-10pm Eastern Time. @aaronburk 
3. Technical information about your production SAML endpoint. If you can generate and send me SP metadata as an XML file, that would be the fastest way for me to prepare the prod change request. @lauraGgit

**Comment by msadakFS** [comment]
Is this dependent on https://trello.com/c/jMz1WKbK/896-generate-a-service-provider-partnership-with-the-production-instance-of-eauth?

**Comment by lauraGgit** [comment]
eAuth unblocked on staging and xml metadata sent off to ICAM/ NITC folks
