### ISSUE TITLE
As a Special Use applicant, I want to be able to log in with login.gov so that I can check on the status of my application

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#150]
## Acceptance Criteria
- [ ]

## Tasks
- [x] Change VCAP endpoint to prod
- [x] Add our application to login.gov production identity provider

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
@hannahkane to ping to see whether we can do this now

**Comment by hannahkane** [comment]
meeting for @lauraGgit and Vishal set up for next week

**Comment by hannahkane** [comment]
Waiting until we've switched over urls

**Comment by lauraGgit** [comment]
This is set on our side, just waiting on login to deploy us to their prod, which happens every other week.
