### ISSUE TITLE
As a SU admin, I would like to see all the information entered correctly into SUDS, so that I don't have to adjust it in SUDS

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#153]
## Acceptance Criteria
- [x] SUAs can view all application info in SUDS
- [X] end to end Temp outfitter as an individual
- [ ] end to end Temp outfitter as an org
- [ ] end to end non-commericial as an org
- [X] end to end non-commericial as an individual
- [ ] Sue approves!

## Tasks
- [ ] Submit applications and debug all fields
- [ ] Complete associated subtasks
- [ ] Fix add'l issues as needed

- [ ] First Name / lastName 
   -- missing from contactPost Submission
        ```
 "method": "POST",
 "uri": " https://nrmwebdev1.fs.usda.gov:8443/sudsws/api/contact/person",
 "json": true,
 "body": {
   "contId": "1-TEST, MIDDLELAYERTEST",
   "firstName": "",
   "lastName": ""
 },
        ```

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
@lauraGgit - apparently I created this issue, but I actually have no recollection of what it means. Is this just about validating that info gets correctly imported into SUDS?

**Comment by lauraGgit** [comment]
We managed to from staging get successful response from suds for both new/existing contacts | tempOutfitter&NC and org/individuals! Middlelayer

**Comment by lauraGgit** [comment]
Waiting on a bit of help from the SUDS folks as to why we can't see the records in SUDS.

**Comment by lauraGgit** [comment]
Temp LLC not valid -b/c Invalid value \"LIMITED LIABILITY COMPANY (LLC)\" for Organization Type - Please re-enter",
   2018-06-29T16:00:55.97-0400 [APP/PROC/WEB/0] ERR     "detailMessage": "us.fed.fs.nrm.dao.DatabaseValidationException: Invalid value \"LIMITED LIABILITY COMPANY (LLC)\" for Organization Typ"

**Comment by lauraGgit** [comment]
`ContID cannot be more than 30 characters long`

**Comment by lauraGgit** [comment]
Noncommercial Org - with short name appears to work
