### ISSUE TITLE
As a user, I want to make sure the integrity of the info in the system is well documented, so that my data is not lost (logging)

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#155]
## Notes
Events list: https://before-you-ship.18f.gov/infrastructure/logging/
X-ref with Paul's list

## Acceptance Criteria
After these events triggers, I can see them in a kibana log.

## Tasks
- [X] Research statements that need to be logged
- [X] Leverage logger created in #169 
- [X] Log DB access fs-middlelayer-api
- [X] Log DB access fs-permit-platform
- [ ] System events - probably covered - shutdowns/ restarts
- [ ] All administrator activity
- [X] permit /created by 
- [X] permit/ modified by
- [X] Data deletions - forest controller / dates/ permits
- [X] Data access - forest controller / dates/ permits
- [X Data changes - forest controller / dates/ permits
- [X] Permission changes - handled at the cloud.gov level
- [X] Log other events in FS-middlelayer-api
- [X] log other events in fs-permit-platform
- [X] get the sequelize logs to be json pretty

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Implemented but need to fix email send thing to fix tests.

**Comment by lauraGgit** [comment]
just need to update the db the `.sequelize.js` Operators deprecation note that has appears for middlelayer
