### ISSUE TITLE
As a user, I should have confidence in the security of the site, so that I use it

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#156]
## Acceptance Criteria
- [ ]

## Tasks
- [X] Generate a checklist based on unaccounted for items in [Before You Ship](https://before-you-ship.18f.gov/ato/checklist/)
- [X] Enable protected branches for the project repository. on both fs-permit-platform/ fs-middlelayer-api @lauraGgit 
- [x] add `snyk` badges to readme on fs-permit-platform @hannahkane 
- [X] add `snyk` badges to readme on fs-middlelayer-api @hannahkane 
- [X] ensure code climate setup on both repositories @lauraGgit 
- [X] add beta 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
@lauraGgit - did you mean to self-reference this ticket in your comment?

**Comment by hannahkane** [comment]
Turns out I can't enable protected branches on fs-middlelayer-api, because I don't have the necessarily permissions, so reassigning to @lauraGgit. master and dev branches of fs-permit-platform are already protected.

**Comment by hannahkane** [comment]
@lauraGgit - I tried to add snyk badges, but I'm getting an error. Looks like it's not detecting a valid manifest file in the root. Can you advise?

**Comment by lauraGgit** [comment]
I'm updating the settings on all of the repos so they should now be marked at open source. this code (with the repo names replaced should work now) [![Known Vulnerabilities](https://snyk.io/test/github/{username}/{repo}/badge.svg)](https://snyk.io/test/github/{username}/{repo})

**Comment by lauraGgit** [comment]
Code climate static code analysis on both repos

**Comment by lauraGgit** [comment]
Moved to Done
