### ISSUE TITLE
As a user, I want to know that an issue preventing the site from working will be resolved quickly, so that I can come back later

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#157]
## Notes
Not needed for ATO; deprioritizing

## Acceptance Criteria
- [ ]

## Tasks
- [x] Figure out how to get New Relic license
- [ ] Configure for ePermits applications

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
