### ISSUE TITLE
As a user, I want the system to be regularly scanned, so that my data isn't compromised

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#158]
## Acceptance Criteria
- [ ]

## Tasks
- [ ] Investigate implementing OWASP into Circle
- [ ] Implement OWASP into Circle

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
