### ISSUE TITLE
As a user, I want to be able to easily identify the site in a google search result, so that I get there fast

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#159]
## Notes
This is implementing a new, memorable URL

## Acceptance Criteria
- [ ]

## Tasks
- [X] Reconfig cloud.gov routes and DNS
- [x] Update manifests to reflect new urls
- [X] Update wikis, 
- [ ] YT video, etc.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Added PR to https://github.com/18F/fs-online-permitting, and separately pushed branch to the wiki (but would need to push to master to see)

**Comment by lauraGgit** [comment]
dgu updated youtube for us
