### ISSUE TITLE
As a potential applicant and applicant, I should see references to the name of the Forest, so that I know what Forest for which I'm applying for a SU permit

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#164]
## Acceptance Criteria
- [x] User sees name of forest on homepage, not just on application form
- [x] User sees name of forest in all email communication
- [x] User sees name of forest on the learn more pages.
- [x] Name is dynamically generated
## Tasks
- [ ] Research to see where name should appear
- [ ] Add name(s) to correct files, header

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Some design is needed to clarify all places where name should appear

**Comment by lauraGgit** [comment]
![image](https://user-images.githubusercontent.com/5840989/43668512-6629ae22-974b-11e8-914e-8e9592cee54e.png)

![image](https://user-images.githubusercontent.com/5840989/43668528-6fbdc306-974b-11e8-8a62-720c050e19a9.png)
