### ISSUE TITLE
As a member of the public, I should see correct contact info, so that I can easily get in touch with the appropriate people

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#165]
## Acceptance Criteria
- [ ] Email address in footer goes to correct FS email address

![Screen Shot 2018-05-07 at 11.39.06 AM.png](https://images.zenhubusercontent.com/568eb686638e718c995fe1f6/db847792-fcbf-4f96-9c74-dc3222cb5b0c)

- [ ] Contact info on "Submitted for review!" pages is correct (both non-commercial, and outfitters/guides)

![Screen Shot 2018-05-07 at 11.39.00 AM.png](https://images.zenhubusercontent.com/568eb686638e718c995fe1f6/2e7f2a8a-b552-4904-8d5d-658d5bb11ac4)

![Screen Shot 2018-05-07 at 11.47.43 AM.png](https://images.zenhubusercontent.com/568eb686638e718c995fe1f6/cd76fb6a-f1e4-442e-94ad-2caf4a2ae9b1)

- [ ] Contact info in emails is correct
![Screen Shot 2018-05-07 at 11.50.51 AM.png](https://images.zenhubusercontent.com/568eb686638e718c995fe1f6/eb03c206-84a8-4000-9187-d929503517b1)

## Tasks
- [ ] Research correct contact info
- [ ] Find all instances of contact info
- [ ] Update all instances

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by aaronburk** [comment]
Sue Sherman-Biery    Special Uses   
--
Forest Service    Mt. Baker-Snoqualmie National Forest    Mt. Baker Ranger District
p: 360-854-2660    c: 360-305-1062    sshermanbiery@fs.fed.us
810 State Route 20   Sedro-Woolley, WA 98284   www.fs.fed.us
Caring   for the land and serving people

**Comment by aaronburk** [comment]
Also change text to say "contact permit Staff at Mount Baker Snoqualmie National Forest"

**Comment by hannahkane** [comment]
can a dev please clarify whether the footer is shared across the entire application, including Christmas trees? If so, we should identify contact info that would be useful for *all* permit types and forests, or perhaps remove contact info from the footer entirely.

**Comment by lauraGgit** [comment]
the footer is app wide. I think that contact should be the broader `Open Forest` support help rather than Forest Specific, unless we go with the forest specific routes.

**Comment by aaronburk** [comment]
There will need to be a discussion at the Brian Schwind level to assign a helpdesk to take these calls/emails

**Comment by aaronburk** [comment]
IF the USFS adopts the helpdesk approach (we will inquire with leadership next week!)

**Comment by hannahkane** [comment]
Moving to blocked until we sort this out!

**Comment by hursey013** [comment]
@hannahkane @msadakFS do we have all of the information for this? I'm working on adding the contact information to the Learn More pages in https://github.com/18F/fs-permit-platform/issues/273 but it's still unclear if what contact information should be associated with the different sections of the site.

**Comment by msadakFS** [comment]
@hannahkane @hursey013 I believe the interim solution was to add the Forest Level contact info for MBS provided in the link below w/o an email address. More research is needed to determine the scale-up solution to this. 

https://www.fs.fed.us/organization/Pacific%20Northwest%20Region%20%28R6%29

**Comment by msadakFS** [comment]
@hannahkane I do not recall there being a resolution on the footer email address. It still states fs-permitting-project@gsa.gov. Is this an issue we icebox or block until we can address an @usda.gov email address to send this to for scale up?
