### ISSUE TITLE
As a user, I want to make sure the software isn't tampered with, so my information isn't stolen (integrity monitoring)

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#167]
## Notes
Tripwire is running on cloud.gov, but doesn't have a mature solution for within a container environment. Some folks within GSA re-deploy nightly so that the files will match what's in github.

(Estimate is for happy path of implementing the chron job)

## Acceptance Criteria
- [ ]

## Tasks
- [x] Check with Paul whether nightly redeploys is an acceptable solution
- [X] If acceptable, implement chron job within Circle for nightly re-deploy
## Definition of Done
- [X] No new security vulnerabilities
- [X] Internal team code review
- [X] Documentation / readme.md / CircleCI updated
- [X] Deployed to master

**Comment by lauraGgit** [comment]
Coordinated with Paul about if ok.

**Comment by lauraGgit** [comment]
@hannahkane it seems like we might already be off of our happy path. Do we want to readjust?

**Comment by lauraGgit** [comment]
Per Paul's comments - nightly restart seems like what we've got for now

**Comment by lauraGgit** [comment]
PRs passing tests in both FS-Middlelayer & platform. Incorporated the nightly recycle and also did some minor circle refactoring because i learned about aliases.

**Comment by hannahkane** [comment]
removing myself from this issue since we got the OK to do the nightly restart.

**Comment by lauraGgit** [comment]
Waiting to see if cf on master will work! 🤞
