### ISSUE TITLE
As a public user, I want to be able to access the public site without having to provide basic auth credentials, so that I can get my permit

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#168]
## Notes
This refers to the basic auth, not the eAuth or login.gov
Just on master deployment

## Acceptance Criteria
- [ ]

## Tasks
- [ ] Update cf-ignore to be branch-dependent within Circle

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
@lauraGgit - is this a duplicate of #160 ?

**Comment by lauraGgit** [comment]
yup - but can we carry over the task back to #160?

**Comment by hannahkane** [comment]
Yup. Closing this as dupe.
