### ISSUE TITLE
As a user, I know that when I unsuccessfully log in, the necessary info for debugging will be logged

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#169]
## Acceptance Criteria
- [ ]

## Tasks
- [X] Add centralized logger to the platform server
- [X] log eauth / login.gov / passport js routes.
- [ ] Add centralized logger to the middlelayer
- [ ] log auth route on middlelayre

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Initial implementation in, now debugging
