### ISSUE TITLE
As a security auditors, I want to prevent non-auditable changes to production apps

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#171]
## Notes
https://cloud.gov/docs/apps/production-ready/#prevent-non-auditable-changes-to-production-apps

## Acceptance Criteria
- [ ]

## Tasks
- [ ]  disable ssh on prod

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
updated readme on https://github.com/18F/fs-cloud-gov-migration/blob/master/README.md
