### ISSUE TITLE
As a system user, I want to be confident that the New Relic account I'm using is valid, so that alerts are actually reported

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#185]
## Acceptance Criteria
- [ ] We have a New Relic account that meets compliance requirements

## Tasks
- [x] Get the account
- [x] Check compliance by talking with Paul
- [ ] Get accounts for those who need it

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by rrefoy** [comment]
Erik is getting this spun up today. Erik wasn't clear on cost as its highly variable.

**Comment by rrefoy** [comment]
@lauraGgit what do we need from Paul? Is it confirmation that FS can use new relic? does he also need access to the account?

**Comment by hannahkane** [comment]
@rrefoy - yes, we need to confirm that FS can use New Relic. We likely want him and Marcus to have accounts. I'll connect you with Paul via email shortly.

**Comment by rrefoy** [comment]
Erik says we are good to go. Laura can also add folks that are outside of TTS.

**Comment by hannahkane** [comment]
@lauraGgit - can you please add Paul, per this morning's meeting? I believe that will close out this ticket.
