### ISSUE TITLE
confirm that auth email that is sent to SUDS isn't being used as what is setting permissions for viewing a SU application

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#193]
## Notes
https://github.com/18F/fs-permit-platform/blob/master/server/src/services/util.es6#L231

Follow how that moves through to SUDS

Consequence: If true, applicant email logged as authorizing official instead of FS employee. 

## Acceptance Criteria
- [ ] The email that is associated with the special use admin authorizing the application is not being set as the applicant's email

## Tasks
- [ ] follow how the auth email gets generated
- [ ] if it is set as the applicant email, update the permit application model in the applicantInfo as well as the model in the middlelayer
- [ ] update how permissions are checked for individual applications in the applicationList view

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Confirmed that this is not being used in investigating #118
