### ISSUE TITLE
Spike: forest-specific routes

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#200]
## Notes
per @lauraGgit:
We might want to reconsider our routing to openforest.fs.usda.gov/mbs/ and then have each permit type being a subroute of that, e.g. openforest.fs.usda.gov/arp/christmas

Consider:
* feasibility of creating these routes now vs. later
* what the UX and IA would be
  * what content would live on openforest.fs.usda.gov/christmas-trees
  * what content would live on openforest.fs.usda.gov/arp
  * how would breadcrumbs work
* how this would impact discoverability and entry points from NF pages like https://www.fs.usda.gov/main/mbs/passes-permits

## Acceptance Criteria
- [ ] We reach a decision about whether to pursue these routes 

## Tasks
- [ ] conduct technical feasibility analysis
- [ ] conduct product impact analysis discussing UX and discoverability/entry points 
- The deliverable will most likely be the creation of a new issue.
## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
How important is it to deal with forest specific url's now or can we do it later?

**Comment by lauraGgit** [comment]
so as a `spike` this would be figuring out whether it is important

**Comment by msadakFS** [comment]
est 2-3 hrs. Don't invest time beyond that.

**Comment by lauraGgit** [comment]
https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts @hursey013 here's the link to it

**Comment by lauraGgit** [comment]
And the `ForestResolver` handles the multiple forests for xmas trees
https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L228
this would be have to be no longer be part of the child but as part of parent route

**Comment by lauraGgit** [comment]
Summary:
## Special uses
- we would have to add and design a page for something at the root `/`
- For special uses: since we are just launching with MBS, the following lines could be manually added to have the `mbs` prefix:
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L54
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L152
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L161
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L170
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L178
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L186
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L195
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L204
## Admin routes
- Special use admin routes should probably be changed to `admin/mbs/special-use-applications`
    - https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L64
- Admin Xmas tree routes, would not need to change.
## User applications
- `user/applications` would not need to change as they would be across forests
## Christmas trees
- probably just change `/christmas-trees/forests` to just `christmas-trees` https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L212
- update the `ForestResolver` to be a prefix rather than a child https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L228
    - change to ':id/christmas-trees/applications/permits/:permitId', https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L273

- lines 284-295 stay the same
