### ISSUE TITLE
As a Special Use applicant, I would like to see emails coming from the system in a consistent HTML template.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#213]
## Notes
The xmas tree emails have an HTML template, let's add that back to special uses.

## Acceptance Criteria
- [x] when an email gets sent for special uses it has the image header from the xmas emails.

## Tasks
- [X] templatize contact info
- [x] templatize NC application info
- [x] templatize temp application info
- [x] HTML for NC applications
- [x] HTML for temp applications
- [x] refactor so that templates are the same by status
- [x] verify that the `review` emails are not just duplicates of `removeHold`

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
`Review` is when the applicant submits new information
`Remove hold` is when the admin removes the hold.

**Comment by msadakFS** [comment]
@lauraGgit The images do not appear in the emails. However, the hyperlinks within the blank boxes work.

![image](https://user-images.githubusercontent.com/39954421/44339676-e23bc000-a447-11e8-8218-34c038b7a068.png)

**Comment by msadakFS** [comment]
![image](https://user-images.githubusercontent.com/39954421/44524371-ddbf1380-a6a2-11e8-8704-65001ce85a4c.png)

Looks good!
