### ISSUE TITLE
Bug: Header content overlapping sidebar

### ISSUE THREAD

**Issue by hursey013** [18F/fs-permit-platform#218]
## Notes
On pages with the floating sidebar menu the top banner overlaps the content when expanded:

![screen shot 2018-06-15 at 3 06 53 pm](https://user-images.githubusercontent.com/1178494/41485364-3f5c287e-70ae-11e8-91f9-282b14ff52b9.png)

## Acceptance Criteria
- [ ] Header no longer overlaps with sidebar

## Tasks
- [ ] Modify CSS Splash style sheet
- [ ] Coordinate with US web design standards 
## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hursey013** [comment]
Add SSL content block to header

**Comment by msadakFS** [comment]
@hursey013 I am still seeing the error. Let me know if I am "jumping the gun" this morning and whether or not this is not ready to be reviewed (by me).

**Comment by lauraGgit** [comment]
@msadakFS this still needs to be reviewed from a code perspective by me. If you're curious what is outstanding on that front, you can take a look at this page: https://github.com/18F/fs-permit-platform/pulls. As you can see, since I have not had time to review, there is a lot that is outstanding.
