### ISSUE TITLE
As a security auditor, I would like to see if the vulnerabilities if snyk fails

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#229]
## Notes
because of how CircleCI is configured if there is a failure on the snyk vulnerability tests the command to upload the vulnerability report will never trigger

recommend consolidating the snyk to a single shell script with the uploads only running on the `nightly` build job
The csv artifact does not load.

## Acceptance Criteria
- [ If the snyk finds vulnerability it will still upload the output to S3]

## Tasks
- [ ] Reconfigure Circle Steps on FS permit platform
- [ ] reconfigure circle steps on fs-middlelayer

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Initial PRs open, but won't be able to verify until failure on master
