### ISSUE TITLE
As a user, I do not want to see horizontal scrollbars in the revision history of my application

### ISSUE THREAD

**Issue by hursey013** [18F/fs-permit-platform#235]
## Notes
Horizontal scrollbars are appearing in the revision history table which could potentially lead to some confusion.

![screen shot 2018-06-22 at 3 07 21 pm](https://user-images.githubusercontent.com/1178494/41794669-0bc0cfc6-762e-11e8-9ab9-2e5eb0cb8bcc.png)

## Acceptance Criteria
- [ ] Scrollbars are not appearing in table in all supported browsers, no matter the width of the window

## Tasks
- [ ] Update relevant CSS

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Which browser is this? I cannot replicate it.

**Comment by hursey013** [comment]
Chrome, it looks like it happens when the email address is over a certain length.
![screen shot 2018-07-18 at 11 42 16 am](https://user-images.githubusercontent.com/1178494/42892379-b03e34b6-8a7f-11e8-8249-3baac3d426fd.png)

**Comment by lauraGgit** [comment]
@hursey013 @msadakFS we can either have it get cut off (`overflow-x:hidden`) or we can  bump the word down and have it wrap. I'm not sure which is preferred. We could also have the revision box go across the whole container.


*Cut off*
![image](https://user-images.githubusercontent.com/5840989/43048864-b97baece-8dbc-11e8-9e9e-eb015454bc4a.png)

*Word wrap*
![image](https://user-images.githubusercontent.com/5840989/43048857-9d228b9e-8dbc-11e8-808c-4577ef07ed47.png)

**Comment by msadakFS** [comment]
@hursey013 @lauraGgit The cutoff is easier to read.

**Comment by hursey013** [comment]
There is also `text-overflow: ellipsis;` which could be a good option in this scenario.
<img width="549" alt="screen shot 2018-07-23 at 9 51 36 am" src="https://user-images.githubusercontent.com/1178494/43080564-fa628fec-8e5d-11e8-879d-8220aceb87a3.png">
