### ISSUE TITLE
As a user, I don't want to see any fake applications

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#236]
## Notes
there are a couple of test applications in the `prod` db, this would be removing them before launch

## Acceptance Criteria
- [ ] No fake applications in the prod db
- [ ] no fake files in the prod s3

## Tasks
- [x] re-nable cf ssh on platform
- [x] test dump in `dev`
- [x] dump application data in db
- [x] delete s3 files
- [ ] disable cf ssh on platform
- [x] re-nable cf ssh on middlelayer
- [x] dump application data in db
- [x] delete s3 data
- [x] disable cf ssh on middlelyaer

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
databases removed- should be remigrated on next build.
