### ISSUE TITLE
As a user, I should understand what other application methods are available to me, in case I prefer them

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-permit-platform#242]
## Notes
Adding this because we'd previously identified a need to include information on the site about how users can still apply for permits using the current offline methods. Given the limited scope of the MBS pilot, I'm not sure this is needed now. 

@msadakFS - if you don't think this is needed for the MBS pilot, perhaps we could consider this when we are getting ready to roll out Christmas Trees.

Consider it as opportunity to train up Xmas content manager.

## Acceptance Criteria
- [ ]

## Tasks
- [ ] talk to forest

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@hannahkane I do not think it is needed now, but we should definitely consider it for the Christmas Tree roll out.

**Comment by lauraGgit** [comment]
Already on Xmas - closing.
