### ISSUE TITLE
As a Special Use Admin, I want to see a contact name in SUDS for applications submitted via ePermit

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-permit-platform#262]
## Notes
contName is an optional parameter in the `/contact` endpoint but is *likel* the field that shows up on an application.

- it is either the `LastName` or the `OrgName` depending on the `OrgType`

## Acceptance Criteria
- [ ] I can see a contact name in SUDS

## Tasks
- [ ] update middlelayer schema
- [ ] update postTranslate tests to ensure that `/contact` includes `contName`
- [ ] update logic for that field

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Cannot test until login.gov is re-established. I cannot see any contact info within any of the applications submitted to SUDS dev.

**Comment by lauraGgit** [comment]
@msadakFS we've had some build issues on the middlelayer-  so this was actually premature to put into PO review. I'll move it back when it can be properly reviewed. 

However, you should be able to submit an application as an admin.

**Comment by lauraGgit** [comment]
Ok, updated this so it should now we should be able to properly test if the name shows up in suds
