### ISSUE TITLE
As a special use administrator, I can see the contact associated with an ePermit application in SUDs.  

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-permit-platform#76]
## Notes
Severity: Moderate - confuses special use administrators
Difficulty of remediation: Unknown

## Acceptance Criteria
- [ ] SUA can see correct contact name associated with submitted application

## Tasks
- [ ] Fire off SU applications and debug!
- [ ] Fix add'l issues as needed

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
@rrefoy - I'm not sure I totally understand this issue, and wondering if you recall enough about this to help me. Is this about displaying info from SUDS in the ePermit app? I'm not sure what the acceptance criteria is, partially because I don't have any visibility into SUDS, so I don't know what contact info we'd be displaying. Is it just a single field? Would it be linked to a SUDS record? Do we have a sense of where it belongs in the information hierarchy?

**Comment by hannahkane** [comment]
This is now duped by #153, so closing
